import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Recycle,ArrowUpRight,ArrowLeft,ArrowRight,Coins,Gift,Trophy,Leaf,ShieldCheck,Home,Camera,Upload,Check,CheckCircle2,X,LogOut,Search,Clock,Users,Package,ClipboardCheck,Settings,BookOpen,History,TrendingUp,GraduationCap,Plus,Trash2,NotebookPen,Milk,ShoppingBag,PenTool,Award,Image as ImageIcon,AlertCircle} from 'lucide-react';
import './style.css';

const fmt=n=>Number(n||0).toLocaleString('th-TH');
const date=s=>new Date(s).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short'});
const statusLabels={'Pending':'รอตรวจสอบ','Approved':'อนุมัติแล้ว','Rejected':'ไม่อนุมัติ','Cancelled':'ยกเลิกแล้ว','Pending Pickup':'รอรับรางวัล','Completed':'รับรางวัลแล้ว'};
const icons={notebook:NotebookPen,bottle:Milk,bag:ShoppingBag,pen:PenTool,badge:Award};
async function api(path,body){let r;try{r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});}catch{throw new Error('เชื่อมต่อไม่ได้ กรุณาลองอีกครั้ง');}const data=await r.json();if(!r.ok)throw new Error(data.error||'โหลดข้อมูลไม่สำเร็จ');return data;}
function Badge({status}){return <span className={'badge '+status.toLowerCase().replaceAll(' ','-')}>{statusLabels[status]||status}</span>}
function RewardArt({reward}){const Icon=icons[reward.icon]||Gift;return <div className="reward-art" style={{background:reward.color||'#e3eddf'}}>{reward.image?<img src={reward.image} alt={reward.name}/>:<Icon size={68} strokeWidth={1.25}/>}<span className="art-label">ECO COLLECTION</span></div>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Empty({text='ยังไม่มีรายการ'}){return <div className="empty"><Leaf size={36}/><p>{text}</p></div>}
function Photo({src,onClick}){return src?<button className="photo" onClick={()=>onClick(src)} aria-label="ขยายภาพหลักฐาน"><img src={src} alt="ภาพขยะที่ส่ง"/></button>:<div className="photo no-photo"><Recycle/><small>ไม่มีรูป</small></div>}
function App(){
 const [page,setPage]=useState('home'),[data,setData]=useState(null),[student,setStudent]=useState(null),[staff,setStaff]=useState(null),[admin,setAdmin]=useState(null),[tab,setTab]=useState('trash'),[adminTab,setAdminTab]=useState('dashboard');
 const [modal,setModal]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[lookup,setLookup]=useState(null),[id,setId]=useState(''),[photo,setPhoto]=useState(''),[category,setCategory]=useState('ขวดพลาสติก'),[note,setNote]=useState(''),[success,setSuccess]=useState(null),[query,setQuery]=useState(''),[period,setPeriod]=useState('overall'),[grade,setGrade]=useState(''),[room,setRoom]=useState(''),[ranks,setRanks]=useState(null),[promotion,setPromotion]=useState([]),[year,setYear]=useState(new Date().getFullYear()),[image,setImage]=useState('');
 const [selectedStudents,setSelectedStudents]=useState([]);
 const inFlight=useRef(false),lastActivity=useRef(Date.now()),operationKey=useRef(null),modalRef=useRef(null),lastFocus=useRef(null),successTimer=useRef(null);
 const refresh=()=>api('public').then(setData);
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[]);
 const clear=()=>{setPage('home');setStudent(null);setStaff(null);setAdmin(null);setLookup(null);setId('');setPhoto('');setNote('');setModal(null);setSuccess(null);setImage('');setQuery('');setRanks(null);setGrade('');setRoom('');setPeriod('overall');setPromotion([]);setSelectedStudents([]);setError('');operationKey.current=null;};
 const home=()=>{clearTimeout(successTimer.current);clear();api('logout',{}).catch(()=>{});refresh().catch(()=>{});};
 useEffect(()=>{const activity=()=>{lastActivity.current=Date.now();};['pointerdown','keydown','input'].forEach(e=>window.addEventListener(e,activity));const timer=setInterval(()=>{if((page!=='home'||modal)&&Date.now()-lastActivity.current>90000){home();setNotice('กลับหน้าหลักและล้างข้อมูลแล้ว เนื่องจากไม่มีการใช้งาน');}},1000);return()=>{clearInterval(timer);['pointerdown','keydown','input'].forEach(e=>window.removeEventListener(e,activity));};},[page,modal?.type]);
 useEffect(()=>{if(notice){let t=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(t);}},[notice]);
 useEffect(()=>{if(!student&&!staff)return;const timer=setInterval(()=>{if(Date.now()-lastActivity.current<30000)api('session',{}).catch(()=>{home();setNotice('หมดเวลาใช้งาน กรุณาระบุตัวตนใหม่');});},30000);return()=>clearInterval(timer);},[student?.id,staff]);
 useEffect(()=>{if(modal?.type!=='identify'||id.length<5||lookup?.id===id)return;let cancelled=false;const timer=setTimeout(()=>{api('identify',{id}).then(p=>{if(!cancelled){setLookup(p);setError('');}}).catch(e=>{if(!cancelled)setError(e.message);});},500);return()=>{cancelled=true;clearTimeout(timer);};},[id,modal?.type]);
 useEffect(()=>{if(modal){lastFocus.current=document.activeElement;setTimeout(()=>modalRef.current?.querySelector('input,button,select')?.focus(),30);}else lastFocus.current?.focus?.();},[modal?.type]);
 async function run(fn){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{inFlight.current=false;setBusy(false);}}
 const action=async(action,payload)=>{const signature=JSON.stringify({action,payload});if(operationKey.current?.signature!==signature)operationKey.current={signature,key:crypto.randomUUID()};let result=await api('action',{action,payload,key:operationKey.current.key});operationKey.current=null;return result;};
 const done=(title,description,code)=>{setModal(null);setStudent(null);setLookup(null);setId('');setPhoto('');setNote('');setSuccess({title,description,code});setPage('success');api('logout',{}).catch(()=>{});refresh().catch(()=>{});successTimer.current=setTimeout(home,12000);};
 async function refreshAdmin(){setAdmin(await api('admin'));await refresh();}
 async function loadStudent(){const result=await api('student');setStudent(result);return result;}
 function identify(next,reward){setError('');setId('');setLookup(null);setModal({type:'identify',next,reward});}
 function navigate(target){if(target==='home'){home();return;}if(staff){setStaff(null);setAdmin(null);api('logout',{}).catch(()=>{});}setError('');setQuery('');if(target==='submit'||target==='account')identify(target);else setPage(target);}
 async function readImage(file,fn){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('เลือกไฟล์ JPG, PNG หรือ WebP');if(file.size>12000000)throw new Error('รูปภาพต้นฉบับต้องไม่เกิน 12 MB');const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>40000000){bitmap.close();throw new Error('ภาพมีความละเอียดสูงเกินไป กรุณาเลือกรูปอื่น');}const canvas=document.createElement('canvas');for(const [side,quality] of [[1280,.78],[1280,.68],[1120,.68],[960,.6]]){const scale=Math.min(1,side/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);const result=canvas.toDataURL('image/jpeg',quality);const encoded=result.slice(result.indexOf(',')+1);const bytes=Math.floor(encoded.length*3/4)-(encoded.endsWith('==')?2:encoded.endsWith('=')?1:0);if(bytes<=400*1024){bitmap.close();fn(result);return;}}bitmap.close();throw new Error('บีบอัดรูปให้ต่ำกว่า 400 KiB ไม่ได้ กรุณาถ่ายใหม่ให้เห็นขยะชัด ๆ');}
 const ranked=(data?.leaderboard||[]).filter(x=>(!grade||x.grade===grade)&&(!room||x.room===room)).sort((a,b)=>(period==='month'?b.monthly-a.monthly:b.earned-a.earned));
 const studentName=id=>admin?.students.find(s=>s.id===id);
 const visibleStudents=admin?.students.filter(s=>[s.name,s.id,'ม.'+s.grade+'/'+s.room,s.grade,s.room].join(' ').toLowerCase().includes(query.toLowerCase()))||[];
 const toggleStudent=id=>setSelectedStudents(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);
 const toggleVisibleStudents=()=>setSelectedStudents(current=>visibleStudents.every(s=>current.includes(s.id))?current.filter(id=>!visibleStudents.some(s=>s.id===id)):[...new Set([...current,...visibleStudents.map(s=>s.id)])]);
 function startPromotion(){setPromotion(admin.students.filter(s=>s.status==='Active').map(s=>({...s,oldGrade:s.grade,grade:String(Math.min(6,Number(s.grade)+1)),status:s.grade==='6'?'Alumni':'Active'})));setAdminTab('promotion');}
 function openModal(value){setError('');setModal(value);}
 const pageTitles={shop:'ร้านรางวัล',leaderboard:'ทำเนียบคนรักษ์โลก',account:'Coins ของฉัน',submit:'ส่งขยะรีไซเคิล'};
 const navItems=[['home',Home,'หน้าหลัก'],['submit',Recycle,'ส่งขยะ'],['account',Coins,'Coins ของฉัน'],['shop',Gift,'ร้านรางวัล'],['leaderboard',Trophy,'อันดับ']];
 const adminNav=[['dashboard',Home,'ภาพรวม'],['reviews',ClipboardCheck,'ตรวจขยะ'],['pickups',Gift,'ส่งมอบรางวัล'],['students',Users,'นักเรียน'],['rewards',Package,'จัดการรางวัล'],['ledger',Coins,'บัญชี Coins'],['promotion',GraduationCap,'เลื่อนชั้น'],['audit',History,'ประวัติเจ้าหน้าที่']];
 function ProfileForm({p,adminMode=false}){return <><Field label="ชื่อ–นามสกุล"><input name="name" required defaultValue={p.name}/></Field><div className="form-grid"><Field label="เลขที่"><input name="number" type="number" min="1" max="60" required defaultValue={p.number||''}/></Field><Field label="ระดับชั้น"><select name="grade" defaultValue={p.grade}>{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></Field><Field label="ห้อง"><input name="room" type="number" min="1" max="30" required defaultValue={p.room}/></Field></div>{adminMode&&<Field label="สถานะ"><select name="status" defaultValue={p.status}>{['Active','Alumni','Transferred','Inactive'].map(s=><option key={s}>{s}</option>)}</select></Field>}</>}
 const submitModal=fn=>e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));run(()=>fn(values));};
 const Button=({children,...props})=><button className="btn primary" disabled={busy} {...props}>{busy?'กำลังดำเนินการ…':children}</button>;
 return <><header><button className="brand" onClick={home}><span className="brand-icon"><Recycle size={27}/></span><span>waste-<span className="brand-light">bank</span><small>SCHOOL RECYCLING CLUB</small></span></button><nav aria-label="เมนูหลัก">{navItems.map(([key,Icon,label])=><button key={key} className={page===key?'active':''} onClick={()=>navigate(key)}><Icon size={19}/><span>{label}</span></button>)}</nav><button className="staff-link" onClick={()=>staff?setPage('admin'):openModal({type:'login'})}><ShieldCheck size={17}/><span>{staff||'เจ้าหน้าที่'}</span></button></header>
 <main>{error&&!modal&&<div className="alert" role="alert"><AlertCircle size={20}/>{error}<button onClick={()=>{setError('');if(!data)refresh().catch(e=>setError(e.message));}}>ลองใหม่</button></div>}
 {!data?<div className="skeleton"><div/><div/><div/></div>:<>
 {page==='home'&&<><div className="eyebrow"><span className="live-dot"/> พื้นที่เล็ก ๆ เพื่อโลกที่ดีขึ้น <span className="date">{new Date().toLocaleDateString('th-TH',{day:'numeric',month:'long',year:'numeric'})}</span></div><section className="home-grid"><div className="hero"><div className="hero-tag"><Leaf size={16}/> SMALL ACTIONS. BIG IMPACT.</div><h1>ขยะของเธอ<br/>มีค่า<span>กว่าที่คิด.</span></h1><p>แยกขยะ สะสม Coins แลกของที่ชอบ<br/>มาเปลี่ยนโรงเรียนให้น่าอยู่ไปด้วยกัน</p><button className="btn lime" onClick={()=>navigate('submit')}>เริ่มส่งขยะ <ArrowUpRight size={23}/></button><button className="btn secondary" onClick={()=>{setModal({type:'register',next:'account'});setError('');}}>สมัครสมาชิกนักเรียน</button><div className="hero-bottom"><span className="mini-avatars">🌱 ♻️ 🌎</span><span>ทุกชิ้นที่แยก คืออีกก้าวที่สำคัญ</span></div><div className="recycle-mark" aria-hidden="true"><Recycle strokeWidth={1.1}/><span>MAKE IT<br/>CIRCULAR</span></div></div><div className="quick-actions"><button className="action-card coin-card" onClick={()=>navigate('account')}><span className="action-icon"><Coins/></span><ArrowUpRight className="corner-arrow"/><div><small>MY ECO WALLET</small><h2>วันนี้มี Coins เท่าไหร่?</h2><p>เช็กยอดสะสมและประวัติของฉัน</p></div></button><button className="action-card shop-card" onClick={()=>navigate('shop')}><span className="action-icon"><Gift/></span><ArrowUpRight className="corner-arrow"/><div><small>A LITTLE THANK YOU</small><h2>ความดีมีของรางวัล</h2><p>เลือกของที่ชอบ แล้วใช้ Coins แลกเลย</p></div></button></div></section>
 <section className="impact"><div><span className="eyebrow">OUR COLLECTIVE IMPACT</span><h3>พลังเล็ก ๆ ของพวกเรา</h3></div><div className="metric"><span className="metric-icon"><Recycle/></span><div><strong>{data.stats.weight.toFixed(1)} <small>กก.</small></strong><p>ขยะที่รีไซเคิลแล้ว</p></div></div><div className="metric"><span className="metric-icon"><Coins/></span><div><strong>{fmt(data.stats.coins)}</strong><p>Coins ที่มอบให้</p></div></div><div className="metric"><span className="metric-icon"><Users/></span><div><strong>{fmt(data.stats.students)} <small>คน</small></strong><p>เพื่อนร่วมรักษ์โลก</p></div></div></section>
 <section className="lower-grid"><div className="how"><div className="section-heading"><h2>เปลี่ยนขยะเป็นรางวัล</h2><span>ง่าย ๆ แค่ 3 ขั้นตอน</span></div><div className="steps">{[[Camera,'แยกแล้วถ่าย','ถ่ายรูปขยะที่แยกไว้'],[ShieldCheck,'รอครูตรวจ','รับ Coins เมื่ออนุมัติ'],[Gift,'แลกของที่ชอบ','รับรางวัลกับคุณครู']].map(([Icon,title,desc],i)=><div key={title}><span className="step-icon"><Icon/><b>0{i+1}</b></span><h4>{title}</h4><p>{desc}</p></div>)}</div></div><div className="top-card"><div className="section-heading"><h2><Trophy size={20}/> Eco heroes</h2><button className="text-button" onClick={()=>setPage('leaderboard')}>ดูทั้งหมด <ArrowRight size={16}/></button></div>{data.leaderboard.slice(0,3).map((p,i)=><div className="mini-rank" key={p.name}><span className={'rank-number rank-'+i}>{i+1}</span><span className="avatar">{p.name.slice(0,1)}</span><div><b>{p.name}</b><small>ม.{p.grade}/{p.room}</small></div><strong>{fmt(p.earned)} <Coins size={14}/></strong></div>)}</div></section></>}
 {['shop','leaderboard','account','submit'].includes(page)&&<div className="page-heading"><div><button className="back" onClick={home}><ArrowLeft size={17}/> หน้าหลัก</button><h1>{pageTitles[page]}</h1></div><span className="privacy"><ShieldCheck size={16}/> กลับหน้าหลักอัตโนมัติเมื่อไม่ใช้งาน 90 วินาที</span></div>}
 {page==='shop'&&<><div className="shop-banner"><span><Gift/> เปลี่ยนความตั้งใจดี ให้เป็นของรางวัลที่ชอบ</span><small>แลกแล้วรับของกับเจ้าหน้าที่ที่จุดรับรางวัล</small></div><div className="rewards-grid">{data.rewards.map(reward=><article className="reward-card" key={reward.id}><RewardArt reward={reward}/><div className="reward-body"><div className="reward-stock">{reward.stock>0?`เหลือ ${reward.stock} ชิ้น`:'ของหมดแล้ว'}{reward.stock>0&&reward.stock<=3&&<span>ใกล้หมด</span>}</div><h2>{reward.name}</h2><p>{reward.description}</p><div className="reward-bottom"><strong><Coins size={21}/>{fmt(reward.price)}</strong><button disabled={!reward.stock} className="btn primary" onClick={()=>identify('redeem',reward)}>แลกรางวัล <ArrowUpRight size={18}/></button></div></div></article>)}</div></>}
 {page==='submit'&&student&&<div className="submit-layout"><section className="panel"><div className="flow-steps"><span className="complete">1 ระบุตัวตน</span><span className="current">2 ส่งหลักฐาน</span><span>3 เสร็จแล้ว</span></div><form onSubmit={e=>{e.preventDefault();run(async()=>{await action('submit',{image:photo,category,note});done('ส่งขยะเรียบร้อย!','รอเจ้าหน้าที่ตรวจสอบ เมื่ออนุมัติแล้ว Coins จะเข้าในบัญชีของเธอ');});}}><div className="upload-zone">{photo?<img className="upload-preview" src={photo} alt="ภาพที่เลือก"/>:<><Camera size={46}/><h3>ถ่ายภาพขยะที่แยกแล้ว</h3><p>ให้เห็นชนิดขยะและจำนวนชัดเจน</p></>}<div className="upload-buttons"><label className="btn primary"><Camera size={18}/> {photo?'ถ่ายใหม่':'เปิดกล้อง'}<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>run(()=>readImage(e.target.files[0],setPhoto))}/></label><label className="btn secondary"><Upload size={18}/> เลือกรูป<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>run(()=>readImage(e.target.files[0],setPhoto))}/></label></div></div><Field label="ประเภทขยะ"><div className="category-grid">{data.categories.map(c=><button key={c} type="button" className={c===category?'selected':''} onClick={()=>setCategory(c)}>{c}</button>)}</div></Field><Field label="ฝากข้อความถึงคุณครู (ไม่บังคับ)"><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={150} placeholder="เช่น ล้างขวดและแกะฉลากแล้ว"/></Field><Button type="submit" style={{width:'100%'}} disabled={busy||!photo}>ส่งขยะให้คุณครูตรวจ <ArrowRight size={19}/></Button></form></section><aside><div className="student-card"><span className="avatar large">{student.name[0]}</span><h2>{student.name}</h2><p>ม.{student.grade}/{student.room} · เลขที่ {student.number||'—'} · {student.id}</p><span className="badge approved"><Check size={14}/> ยืนยันบัญชีแล้ว</span></div><div className="tip"><Leaf/><h3>แยกนิดเดียว ช่วยโลกได้เยอะ</h3><p>เทน้ำออก ล้างให้สะอาด และแยกตามประเภทก่อนส่งทุกครั้ง</p><small>Coins จะได้รับหลังจากเจ้าหน้าที่ตรวจแล้วเท่านั้น</small></div></aside></div>}
 {page==='account'&&student&&<><div className="wallet"><div><span className="eyebrow">MY ECO WALLET</span><h2>{student.name}</h2><p>ม.{student.grade}/{student.room} · เลขที่ {student.number||'—'} · รหัส {student.id}</p><button className="btn ghost" onClick={()=>openModal({type:'profile',p:student})}>แก้ไขโปรไฟล์</button></div><div className="wallet-balance"><span>Coins ที่ใช้ได้</span><strong><Coins size={40}/>{fmt(student.balance)}</strong></div><div className="wallet-stats"><p>สะสมทั้งหมด <b>{fmt(student.earned)}</b></p><p>อันดับโรงเรียน <b>#{student.rank}</b></p><p>ส่งขยะสำเร็จ <b>{student.submissions.filter(x=>x.status==='Approved').length} ครั้ง</b></p></div></div><div className="tabs">{[['trash','ประวัติส่งขยะ'],['coins','ประวัติ Coins'],['rewards','ประวัติรางวัล']].map(([t,label])=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{label}</button>)}</div><div className="panel">{tab==='trash'&&<>{!student.submissions.length&&<Empty/>}{student.submissions.map(s=><div className="history-row" key={s.id}><Photo src={s.image} onClick={setImage}/><div className="grow"><b>{s.category}</b><small>{date(s.at)}</small>{s.reason&&<p className="reason">{s.reason}</p>}{s.evidenceRemovedAt&&<small>ภาพถูกลบตามระยะเวลาเก็บรักษา</small>}</div><Badge status={s.status}/><strong>{s.coins?`+${s.coins}`:'—'}</strong>{s.status==='Pending'&&<button className="text-button danger" onClick={()=>openModal({type:'cancelSubmission',item:s})}>ยกเลิก</button>}</div>)}</>}{tab==='coins'&&<>{!student.ledger.length&&<Empty/>}{student.ledger.map(t=><div className="ledger-row" key={t.id}><span className={'transaction-icon '+(t.amount<0?'debit':'')}><Coins/></span><div className="grow"><b>{t.reason}</b><small>{date(t.at)}{t.staff?' · '+t.staff:''}</small></div><strong className={t.amount<0?'danger':'positive'}>{t.amount>0?'+':''}{fmt(t.amount)}</strong></div>)}</>}{tab==='rewards'&&<>{!student.redemptions.length&&<Empty/>}{student.redemptions.map(r=><div className="history-row" key={r.id}><span className="transaction-icon"><Gift/></span><div className="grow"><b>{r.name}</b><small>{date(r.at)}</small><code>{r.code}</code></div><Badge status={r.status}/><strong>{r.cost} Coins</strong></div>)}</>}</div></>}
 {page==='leaderboard'&&<><div className="leader-intro"><span className="hero-tag"><Trophy size={17}/> EVERY LITTLE ACTION COUNTS</span><h2>เก่งมากเลย เหล่าฮีโร่รักษ์โลก!</h2><p>อันดับจาก Coins ที่สะสมได้ · ใช้ Coins แลกรางวัลแล้วอันดับไม่ลด</p></div><div className="filters"><div className="tabs compact">{[['overall','ทั้งหมด'],['month','เดือนนี้'],['grade','ระดับชั้น'],['class','ห้องเรียน']].map(([t,label])=><button className={period===t?'active':''} key={t} onClick={()=>{setPeriod(t);setRanks(null);}}>{label}</button>)}</div><select aria-label="กรองระดับชั้น" value={grade} onChange={e=>{setGrade(e.target.value);setRanks(null);}}><option value="">ทุกระดับชั้น</option>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>ม.{n}</option>)}</select><select aria-label="กรองห้อง" value={room} onChange={e=>{setRoom(e.target.value);setRanks(null);}}><option value="">ทุกห้อง</option>{[1,2,3].map(n=><option key={n} value={n}>ห้อง {n}</option>)}</select></div><div className="podium">{ranked.slice(0,3).map((p,i)=><div className={'podium-card podium-'+i} key={p.name}><span className="medal">{['🥇','🥈','🥉'][i]}</span><div className="avatar large">{p.name[0]}</div><h3>{p.name}</h3><p>ม.{p.grade}/{p.room}</p><strong>{fmt(period==='month'?p.monthly:p.earned)} <Coins size={20}/></strong></div>)}</div><div className="panel"><div className="section-heading"><h2>10 อันดับรักษ์โลก</h2><span>{period==='month'?'เฉพาะเดือนนี้ ไม่รีเซ็ตยอด Coins':'ยอดสะสมตลอดกิจกรรม'}</span></div>{ranked.slice(0,10).map((p,i)=><div className="leader-row" key={p.name}><b className="rank-number">{i+1}</b><span className="avatar">{p.name[0]}</span><b className="grow">{p.name}</b><span>ม.{p.grade}/{p.room}</span><strong>{fmt(period==='month'?p.monthly:p.earned)} <Coins size={17}/></strong></div>)}{!ranked.length&&<Empty/>}<form className="search-form" onSubmit={e=>{e.preventDefault();run(async()=>setRanks(await api('rank?'+new URLSearchParams({q:query,period,grade,room}))));}}><Search/><input aria-label="ค้นหาอันดับ" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาอันดับของเธอด้วยชื่อหรือรหัสนักเรียน" required/><button className="btn primary">ค้นหา</button></form>{ranks&&(!ranks.length?<Empty text="ไม่พบชื่อในเงื่อนไขนี้"/>:ranks.map(p=><div className="leader-row" key={p.rank}><b>#{p.rank}</b><span className="grow">{p.name} · ม.{p.grade}/{p.room}</span><strong>{fmt(p.earned)} Coins</strong></div>))}</div></>}
 {page==='success'&&success&&<div className="success-screen"><div className="success-icon"><CheckCircle2 size={64}/></div><span className="eyebrow">ONE MORE GOOD THING FOR OUR PLANET</span><h1>{success.title}</h1><p>{success.description}</p>{success.code&&<div className="pickup-code"><span>รหัสรับรางวัล · แสดงให้เจ้าหน้าที่</span><strong>{success.code}</strong><small>ดูรหัสนี้อีกครั้งได้ในประวัติรางวัล</small></div>}<button className="btn primary" onClick={home}>กลับหน้าหลัก <Home size={18}/></button><small>หน้าจอนี้จะปิดอัตโนมัติภายใน 12 วินาที</small></div>}
 {page==='admin'&&admin&&<div className="admin-layout"><aside className="admin-sidebar"><span className="eyebrow">STAFF WORKSPACE</span><h2>{staff}</h2>{adminNav.map(([key,Icon,label])=><button key={key} className={adminTab===key?'active':''} onClick={()=>{setQuery('');key==='promotion'?startPromotion():setAdminTab(key);}}><Icon size={20}/>{label}{key==='reviews'&&<span className="count">{admin.submissions.filter(s=>s.status==='Pending').length}</span>}</button>)}<button className="logout" onClick={home}><LogOut size={18}/> ออกจากระบบ</button></aside><section className="admin-content"><div className="page-heading"><h1>{adminNav.find(x=>x[0]===adminTab)?.[2]}</h1><button className="btn secondary" onClick={()=>run(refreshAdmin)}>รีเฟรช</button></div>
 {adminTab==='dashboard'&&<div className="panel"><h3>Google Drive</h3><p>{admin.drive?.connected?'เชื่อมแล้ว — รูปใหม่เก็บใน Drive':admin.drive?.configured?'ตั้งค่า OAuth แล้ว แต่ยังไม่ได้เชื่อมบัญชี':'ยังไม่ตั้งค่า OAuth ใน .env — รูปยังเก็บใน SQLite'}</p>{admin.drive?.configured&&!admin.drive?.connected&&<a className="btn secondary" href="/api/drive/connect">เชื่อมบัญชี Google Drive</a>}</div>}
 {adminTab==='dashboard'&&<><div className="dashboard-stats">{[['รอตรวจขยะ',admin.submissions.filter(s=>s.status==='Pending').length,ClipboardCheck,'reviews'],['รอรับรางวัล',admin.redemptions.filter(s=>s.status==='Pending Pickup').length,Gift,'pickups'],['นักเรียน Active',admin.students.filter(s=>s.status==='Active').length,Users,'students'],['ของใกล้หมด',admin.rewards.filter(r=>r.stock<=3).length,Package,'rewards']].map(([label,value,Icon,target])=><button className="stat-card" key={label} onClick={()=>setAdminTab(target)}><Icon/><strong>{value}</strong><span>{label}</span></button>)}</div><div className="panel"><div className="section-heading"><h2>วันนี้ทำสิ่งดีไปเท่าไหร่?</h2><TrendingUp/></div><div className="today-stats"><div><strong>{admin.submissions.filter(s=>s.status==='Approved'&&new Date(s.reviewedAt||s.at).toDateString()===new Date().toDateString()).length}</strong><p>รายการที่อนุมัติวันนี้</p></div><div><strong>{fmt(admin.ledger.filter(t=>t.type==='recycle'&&new Date(t.at).toDateString()===new Date().toDateString()).reduce((n,t)=>n+t.amount,0))}</strong><p>Coins ที่มอบวันนี้</p></div></div><h3>สัดส่วนขยะที่ผ่านการตรวจ</h3>{data.categories.map(c=>{const count=admin.submissions.filter(s=>s.status==='Approved'&&s.category===c).length;return <div className="bar-row" key={c}><span>{c}</span><div><i style={{width:Math.max(0,count/Math.max(1,admin.submissions.filter(s=>s.status==='Approved').length)*100)+'%'}}/></div><b>{count}</b></div>;})}</div><div className="panel"><h2>กิจกรรมล่าสุด</h2>{admin.audit.slice(0,5).map(a=><div className="ledger-row" key={a.id}><History/><div className="grow"><b>{a.action} · {a.staff}</b><small>{a.target} · {date(a.at)}</small></div></div>)}</div></>}
 {adminTab==='reviews'&&<><p className="muted">ตรวจหลักฐาน ชั่งน้ำหนัก และระบุ Coins ก่อนอนุมัติ</p><div className="review-grid">{admin.submissions.filter(s=>s.status==='Pending').map(s=>{const p=studentName(s.student);return <article className="panel review-card" key={s.id}><Photo src={s.image} onClick={setImage}/><Badge status={s.status}/><h3>{s.category}</h3><b>{p?.name}</b><p>{s.student} · ม.{p?.grade}/{p?.room}</p><small>{date(s.at)}</small><p>{s.note||'ไม่มีหมายเหตุ'}</p><div className="button-row"><button className="btn primary" onClick={()=>openModal({type:'review',item:s,status:'Approved'})}>อนุมัติ</button><button className="btn secondary danger" onClick={()=>openModal({type:'review',item:s,status:'Rejected'})}>ไม่อนุมัติ</button></div></article>;})}</div>{!admin.submissions.some(s=>s.status==='Pending')&&<Empty text="ตรวจครบแล้ว ขอบคุณที่ช่วยดูแลโลก!"/>}</>}
 {adminTab==='pickups'&&<><input className="search-input" aria-label="ค้นหาการรับรางวัล" placeholder="ค้นหาชื่อ รหัสนักเรียน หรือรหัสรับรางวัล" value={query} onChange={e=>setQuery(e.target.value)}/>{admin.redemptions.filter(r=>r.status==='Pending Pickup'&&[r.code,r.student,studentName(r.student)?.name].join(' ').toLowerCase().includes(query.toLowerCase())).map(r=><div className="panel pickup-row" key={r.id}><Gift size={32}/><div className="grow"><h3>{r.name} · {r.cost} Coins</h3><b>{studentName(r.student)?.name}</b><p>{r.student} · ม.{studentName(r.student)?.grade}/{studentName(r.student)?.room}</p><code>{r.code}</code><small>{date(r.at)}</small></div><button className="btn primary" onClick={()=>openModal({type:'handover',item:r})}>ยืนยันส่งมอบ</button><button className="text-button danger" onClick={()=>openModal({type:'cancelReward',item:r})}>ยกเลิกและคืน Coins</button></div>)}{!admin.redemptions.some(r=>r.status==='Pending Pickup')&&<Empty/>}</>}
 {adminTab==='students'&&<><div className="student-tools"><input className="search-input" aria-label="ค้นหานักเรียน" placeholder="ค้นหาชื่อ รหัส ชั้น หรือห้อง" value={query} onChange={e=>setQuery(e.target.value)}/><button className="btn secondary danger" disabled={!selectedStudents.length||busy} onClick={()=>openModal({type:'deleteStudents',ids:selectedStudents.filter(id=>admin.students.some(s=>s.id===id))})}><Trash2 size={17}/> ลบที่เลือก ({selectedStudents.length})</button></div><div className="table-wrap"><table><thead><tr><th><input type="checkbox" aria-label="เลือกนักเรียนทั้งหมดที่แสดง" checked={visibleStudents.length>0&&visibleStudents.every(s=>selectedStudents.includes(s.id))} onChange={toggleVisibleStudents} disabled={!visibleStudents.length}/></th><th>นักเรียน</th><th>ชั้น / ห้อง</th><th>สถานะ</th><th>Coins</th><th>จัดการ</th></tr></thead><tbody>{visibleStudents.map(s=><tr key={s.id}><td><input type="checkbox" aria-label={'เลือก '+s.name} checked={selectedStudents.includes(s.id)} onChange={()=>toggleStudent(s.id)}/></td><td><b>{s.name}</b><small>เลขที่ {s.number||'—'} · {s.id}</small></td><td>ม.{s.grade}/{s.room}</td><td>{s.status}</td><td>{fmt(s.balance)}</td><td><div className="button-row"><button className="text-button" onClick={()=>run(async()=>{const p=await api('student?id='+s.id);openModal({type:'studentDetail',p});})}>ดูประวัติ</button><button className="text-button" onClick={()=>openModal({type:'profile',p:s,adminMode:true})}>แก้ไข</button><button className="text-button" onClick={()=>openModal({type:'adjust',p:s})}>ปรับ Coins</button></div></td></tr>)}</tbody></table></div></>}
 {adminTab==='rewards'&&<><button className="btn primary" onClick={()=>openModal({type:'reward',item:{name:'',description:'',price:100,stock:0,enabled:true,image:''}})}><Plus size={18}/> เพิ่มรางวัล</button><div className="rewards-grid admin-rewards">{admin.rewards.map(r=><article className="reward-card" key={r.id}><RewardArt reward={r}/><div className="reward-body"><h3>{r.name}</h3><p>{r.price} Coins · เหลือ {r.stock} ชิ้น</p><p>{r.enabled?'เปิดให้แลก':'ปิดให้แลก'}{r.stock<=3?' · สต็อกต่ำ':''}</p><button className="btn secondary" onClick={()=>openModal({type:'reward',item:r})}>แก้ไขรางวัล</button></div></article>)}</div></>}
 {adminTab==='ledger'&&<><input className="search-input" aria-label="ค้นหา Coins" placeholder="ค้นหารหัสนักเรียน เหตุผล หรือประเภท" value={query} onChange={e=>setQuery(e.target.value)}/><div className="panel">{[...admin.ledger].reverse().filter(t=>[t.student,t.reason,t.type].join(' ').includes(query)).map(t=><div className="ledger-row" key={t.id}><Coins/><div className="grow"><b>{t.reason}</b><small>{studentName(t.student)?.name} · {t.student} · {date(t.at)}</small><small>{t.type} · {t.staff||'นักเรียน'}{t.related?' · อ้างอิง '+t.related.slice(0,8):''}</small></div><strong className={t.amount<0?'danger':'positive'}>{t.amount>0?'+':''}{fmt(t.amount)}</strong></div>)}</div></>}
 {adminTab==='audit'&&<><div className="filters"><input className="search-input" aria-label="ค้นหา Audit" placeholder="ค้นหาเจ้าหน้าที่ รายการ หรือเหตุผล" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="ประเภท Audit" value={category.startsWith('audit:')?category.slice(6):''} onChange={e=>setCategory('audit:'+e.target.value)}><option value="">ทุกการกระทำ</option>{[...new Set(admin.audit.map(a=>a.action))].map(a=><option key={a}>{a}</option>)}</select></div><div className="panel">{admin.audit.filter(a=>JSON.stringify(a).includes(query)&&(!category.startsWith('audit:')||!category.slice(6)||a.action===category.slice(6))).map(a=><div className="audit-row" key={a.id}><div><b>{a.action}</b><span>{a.staff} · {date(a.at)}</span></div><p>{a.target}{a.reason?' · '+a.reason:''}</p><div className="audit-values"><code>{JSON.stringify(a.before)}</code><ArrowRight size={16}/><code>{JSON.stringify(a.after)}</code></div></div>)}</div></>}
 {adminTab==='promotion'&&<><div className="panel"><h2>ตรวจสอบก่อนขึ้นปีการศึกษาใหม่</h2><p>ปรับชั้น ห้อง และสถานะรายคนได้ Coins และประวัติทั้งหมดจะคงอยู่</p><Field label="ปีการศึกษา (ค.ศ.)"><input type="number" min="2026" max="2100" value={year} onChange={e=>setYear(e.target.value)}/></Field><div className="promotion-summary">{[1,2,3,4,5,6].map(g=><span key={g}>ม.{g} → {g===6?'ศิษย์เก่า':'ม.'+(g+1)}<b>{promotion.filter(p=>p.oldGrade===String(g)).length} คน</b></span>)}</div><div className="table-wrap"><table><thead><tr><th>นักเรียน</th><th>ชั้นเดิม</th><th>ชั้นใหม่</th><th>ห้อง</th><th>สถานะ</th></tr></thead><tbody>{promotion.map((p,i)=><tr key={p.id}><td>{p.name}</td><td>ม.{p.oldGrade}</td><td><select aria-label={'ชั้นใหม่ '+p.name} value={p.grade} onChange={e=>setPromotion(old=>old.map((s,j)=>j===i?{...s,grade:e.target.value}:s))}>{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></td><td><input aria-label={'ห้อง '+p.name} type="number" min="1" max="30" value={p.room} onChange={e=>setPromotion(old=>old.map((s,j)=>j===i?{...s,room:e.target.value}:s))}/></td><td><select aria-label={'สถานะ '+p.name} value={p.status} onChange={e=>setPromotion(old=>old.map((s,j)=>j===i?{...s,status:e.target.value}:s))}>{['Active','Alumni','Transferred','Inactive'].map(t=><option key={t}>{t}</option>)}</select></td></tr>)}</tbody></table></div><Button onClick={()=>openModal({type:'promote'})} disabled={!promotion.length||busy}>ตรวจสอบครบแล้ว · เลื่อนชั้น {promotion.length} คน</Button></div></>}
 </section></div>}
 </>}
 </main><footer><span><Recycle size={17}/> WASTE-BANK <span className="footer-separator">/</span> ทำสิ่งเล็ก ๆ ให้โลกทุกวัน</span><span>พัฒนาโดย ประกาศิต สุริยะ</span></footer>
 {notice&&<div className="toast" role="status"><CheckCircle2 size={20}/>{notice}</div>}
 {modal&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy)setModal(null);}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" ref={modalRef} onKeyDown={e=>{if(e.key==='Escape'&&!busy)setModal(null);if(e.key==='Tab'){const els=[...modalRef.current.querySelectorAll('button:not(:disabled),input:not(:disabled),select,textarea,[tabindex="0"]')];let first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><button className="modal-close" aria-label="ปิด" disabled={busy} onClick={()=>setModal(null)}><X/></button>
 {modal.type==='identify'&&<><span className="modal-symbol"><Users/></span><h2 id="modal-title">เข้าสู่ระบบนักเรียน</h2><p className="muted">ใส่เลขประจำตัวนักเรียนเพื่อดูบัญชีเดิม</p><form onSubmit={submitModal(async()=>{if(!lookup){setLookup(await api('identify',{id}));return;}await loadStudent();const next=modal.next;if(next==='redeem'){setModal({type:'redeem',reward:modal.reward});}else{setPage(next);setModal(null);setCategory('ขวดพลาสติก');}})}><Field label="เลขประจำตัวนักเรียน"><input autoFocus inputMode="numeric" value={id} onChange={e=>{const value=e.target.value.replace(/\D/g,'').slice(0,10);setId(value);setLookup(null);}} required placeholder="เลขประจำตัวนักเรียน"/></Field>{lookup&&<div className="identity"><span className="avatar">{lookup.name[0]}</span><div><b>{lookup.name}</b><p>ม.{lookup.grade}/{lookup.room} · เลขที่ {lookup.number||'—'}</p></div><CheckCircle2/></div>}<Button type="submit">{lookup?'ใช่ นี่คือบัญชีของฉัน':'ตรวจสอบรหัส'} <ArrowRight size={18}/></Button></form><p className="muted">ยังไม่มีบัญชี?</p><button className="btn secondary" onClick={()=>setModal({...modal,type:'register'})}>สมัครสมาชิกใหม่</button></>}
 {modal.type==='register'&&<><span className="modal-symbol"><Users/></span><h2 id="modal-title">สมัครสมาชิกนักเรียน</h2><p className="muted">กรอกข้อมูลนักเรียน ไม่มีรหัสผ่าน</p><form onSubmit={submitModal(async v=>{await api('register',v);await loadStudent();await refresh();const next=modal.next;if(next==='redeem'){setModal({type:'redeem',reward:modal.reward});}else{setPage(next);setModal(null);setCategory('ขวดพลาสติก');}})}><Field label="ชื่อ–นามสกุล"><input name="name" autoFocus required maxLength="80" placeholder="ชื่อและนามสกุล"/></Field><div className="form-grid"><Field label="เลขที่"><input name="number" type="number" min="1" max="60" required placeholder="เช่น 12"/></Field><Field label="เลขประจำตัวนักเรียน"><input name="id" inputMode="numeric" pattern="[0-9]{5,10}" maxLength="10" required placeholder="เช่น 65123"/></Field></div><div className="form-grid"><Field label="ระดับชั้น"><select name="grade" required defaultValue=""><option value="" disabled>เลือก ม.</option>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>ม.{n}</option>)}</select></Field><Field label="ห้อง"><input name="room" type="number" min="1" max="30" required placeholder="เช่น 2"/></Field></div><Button type="submit">สมัครสมาชิก <ArrowRight size={18}/></Button></form><button className="text-button" onClick={()=>setModal({...modal,type:'identify'})}>มีบัญชีแล้ว? เข้าสู่ระบบ</button></>}
 {modal.type==='login'&&<><span className="modal-symbol"><ShieldCheck/></span><h2 id="modal-title">สำหรับเจ้าหน้าที่</h2><p className="muted">ใช้บัญชีและ PIN ของเจ้าหน้าที่แต่ละคน</p><form onSubmit={submitModal(async v=>{const result=await api('login',v);setStaff(result.name);await refreshAdmin();setPage('admin');setAdminTab('dashboard');setModal(null);})}><Field label="บัญชีเจ้าหน้าที่"><input name="id" autoComplete="username" required placeholder="ชื่อบัญชีเจ้าหน้าที่"/></Field><Field label="PIN ส่วนตัว"><input name="pin" type="password" inputMode="numeric" autoComplete="current-password" required/></Field><Button>เข้าสู่ระบบ <ArrowRight size={18}/></Button></form></>}
 {modal.type==='redeem'&&<><span className="modal-symbol"><Gift/></span><h2 id="modal-title">ยืนยันแลกรางวัล</h2><div className="redemption-summary"><b>{modal.reward.name}</b><strong>{modal.reward.price} Coins</strong></div><p>{student?.name} · ยอดคงเหลือ {fmt(student?.balance)} Coins</p><p className="muted">แลกสำเร็จแล้ว กรุณารับของกับเจ้าหน้าที่</p><form onSubmit={submitModal(async v=>{const result=await action('redeem',{id:modal.reward.id});done('จองรางวัลแล้ว!','Coins ถูกหักเรียบร้อย สถานะ: รอรับรางวัล',result.code);})}><Button disabled={busy||(student?.balance<modal.reward.price)}>ยืนยันแลก {modal.reward.price} Coins</Button>{student?.balance<modal.reward.price&&<p className="danger">Coins ยังไม่เพียงพอ มาแยกขยะเพิ่มกัน!</p>}</form></>}
 {modal.type==='cancelSubmission'&&<><h2 id="modal-title">ยกเลิกการส่งขยะ?</h2><p>{modal.item.category} · รายการนี้จะไม่ถูกตรวจเพื่อรับ Coins</p><form onSubmit={submitModal(async v=>{await action('cancelSubmission',{id:modal.item.id});done('ยกเลิกรายการแล้ว','สามารถส่งหลักฐานใหม่ได้จากหน้าหลัก');})}><Button>ยืนยันยกเลิก</Button></form></>}
 {modal.type==='profile'&&<><h2 id="modal-title">แก้ไขข้อมูลนักเรียน</h2><form onSubmit={submitModal(async v=>{await action('profile',{...v,id:modal.p.id});if(modal.adminMode){await refreshAdmin();setModal(null);setNotice('บันทึกข้อมูลแล้ว');}else done('บันทึกข้อมูลแล้ว','ข้อมูลโปรไฟล์ได้รับการอัปเดตเรียบร้อย');})}><ProfileForm p={modal.p} adminMode={modal.adminMode}/><Button>บันทึกข้อมูล</Button></form></>}
 {modal.type==='deleteStudents'&&<><h2 id="modal-title">ลบนักเรียน {modal.ids.length} คน?</h2><p>ข้อมูลนักเรียน Coins ประวัติส่งขยะ ประวัติรางวัล และรูปหลักฐานที่เกี่ยวข้องจะถูกลบ ไม่สามารถกู้คืนจากหน้าเว็บได้</p><div className="delete-student-list">{modal.ids.map(id=><span key={id}>{admin.students.find(s=>s.id===id)?.name} · {id}</span>)}</div><form onSubmit={submitModal(async v=>{const result=await action('deleteStudents',{ids:modal.ids,confirm:v.confirm==='on'});await refreshAdmin();setSelectedStudents([]);setModal(null);setNotice(result.imageCleanupPending?`ลบนักเรียน ${result.deleted} คนแล้ว รูปใน Drive อีก ${result.imageCleanupPending} รูปรอลบอัตโนมัติ`:`ลบนักเรียน ${result.deleted} คนและข้อมูลที่เกี่ยวข้องแล้ว`);})}><label className="checkbox"><input name="confirm" type="checkbox" required/> ยืนยันว่าตรวจรายชื่อแล้วและต้องการลบข้อมูลเหล่านี้</label><Button>ยืนยันลบ {modal.ids.length} คน</Button></form></>}
 {modal.type==='review'&&<><h2 id="modal-title">{modal.status==='Approved'?'อนุมัติการส่งขยะ':'ไม่อนุมัติรายการ'}</h2><p>{modal.item.category} · {studentName(modal.item.student)?.name}</p><form onSubmit={submitModal(async v=>{await action('review',{...v,id:modal.item.id,status:modal.status});await refreshAdmin();setModal(null);setNotice('บันทึกผลตรวจแล้ว');})}>{modal.status==='Approved'?<><Field label="Coins ที่มอบให้"><input name="coins" type="number" min="1" max="10000" required defaultValue="50"/></Field><Field label="น้ำหนักที่ชั่งจริง (กก.)"><input name="weight" type="number" min="0.001" max="1000" step="0.001" required placeholder="0.50"/></Field></>:<Field label="เหตุผลที่ไม่อนุมัติ"><textarea name="reason" required minLength={3} maxLength={150} placeholder="เช่น ภาพไม่ชัด ไม่เห็นขยะ หรือส่งซ้ำ"/></Field>}<Button>ยืนยันผลการตรวจ</Button></form></>}
 {['handover','cancelReward'].includes(modal.type)&&<><h2 id="modal-title">{modal.type==='handover'?'ยืนยันส่งมอบรางวัล':'ยกเลิกและคืน Coins'}</h2><p>{modal.item.name} · {studentName(modal.item.student)?.name}</p><code>{modal.item.code}</code><form onSubmit={submitModal(async v=>{await action(modal.type,{id:modal.item.id,verified:v.verified==='on',reason:v.reason});await refreshAdmin();setModal(null);setNotice('บันทึกรายการแล้ว');})}>{modal.type==='handover'?<label className="checkbox"><input name="verified" type="checkbox" required/> ตรวจสอบบัตรนักเรียนและส่งมอบของแล้ว</label>:<><p>คืน {modal.item.cost} Coins และคืนสินค้า 1 ชิ้นเข้าสู่สต็อก</p><Field label="เหตุผล"><textarea name="reason" required minLength={3}/></Field></>}<Button>ยืนยัน</Button></form></>}
 {modal.type==='adjust'&&<><h2 id="modal-title">ปรับ Coins</h2><p>{modal.p.name} · ยอดปัจจุบัน {fmt(modal.p.balance)} Coins</p><form onSubmit={submitModal(async v=>{await action('adjust',{...v,id:modal.p.id,confirmLarge:v.confirmLarge==='on'});await refreshAdmin();setModal(null);setNotice('สร้างรายการปรับ Coins แล้ว');})}><Field label="จำนวน (+ เพิ่ม / − ลด)"><input name="amount" type="number" min="-100000" max="100000" required onChange={e=>{const n=Number(e.target.value);e.target.form.querySelector('output').textContent='ยอดใหม่: '+fmt(modal.p.balance+n)+' Coins';}}/></Field><output>ยอดใหม่: {fmt(modal.p.balance)} Coins</output><Field label="เหตุผล"><textarea name="reason" minLength={3} required/></Field><label className="checkbox"><input name="confirmLarge" type="checkbox"/> ยืนยันเพิ่มเติมเมื่อปรับตั้งแต่ 1,000 Coins</label><Button>ยืนยันและบันทึกในบัญชี</Button></form></>}
 {modal.type==='reward'&&<><h2 id="modal-title">{modal.item.id?'แก้ไข':'เพิ่ม'}รางวัล</h2><form onSubmit={submitModal(async v=>{await action('reward',{...v,id:modal.item.id,icon:modal.item.icon,image:modal.item.image,enabled:v.enabled==='on'});await refreshAdmin();setModal(null);setNotice('บันทึกรางวัลแล้ว');})}><Field label="ชื่อรางวัล"><input name="name" required defaultValue={modal.item.name}/></Field><Field label="รายละเอียด"><textarea name="description" defaultValue={modal.item.description}/></Field><div className="form-grid"><Field label="ราคา Coins"><input name="price" type="number" min="1" required defaultValue={modal.item.price}/></Field><Field label="สต็อกที่เหลือ"><input name="stock" type="number" min="0" required defaultValue={modal.item.stock}/></Field></div><Field label="รูปสินค้า"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>run(()=>readImage(e.target.files[0],value=>setModal(m=>({...m,item:{...m.item,image:value}}))))}/></Field>{modal.item.image&&<img className="small-preview" src={modal.item.image} alt="รูปสินค้า"/>}<label className="checkbox"><input type="checkbox" name="enabled" defaultChecked={modal.item.enabled}/> เปิดให้แลกรางวัล</label><Button>บันทึกรางวัล</Button></form></>}
 {modal.type==='promote'&&<><h2 id="modal-title">ยืนยันเลื่อนชั้นนักเรียน</h2><p>ปี {year} · ทั้งหมด {promotion.length} คน</p><p>ตรวจข้อยกเว้นในตารางแล้วหรือยัง? ปีนี้จะเลื่อนชั้นซ้ำอีกไม่ได้</p><Button onClick={()=>run(async()=>{await action('promote',{year,students:promotion.map(({id,grade,room,status})=>({id,grade,room,status})),confirm:true});await refreshAdmin();setModal(null);setAdminTab('students');setNotice('เลื่อนชั้นเรียบร้อย ประวัติและ Coins คงเดิม');})}>ยืนยันเลื่อนชั้น</Button></>}
 {modal.type==='studentDetail'&&<><h2 id="modal-title">{modal.p.name}</h2><p>ม.{modal.p.grade}/{modal.p.room} · เลขที่ {modal.p.number||'—'} · {modal.p.status} · อันดับ #{modal.p.rank}</p><h3>{fmt(modal.p.balance)} Coins · สะสม {fmt(modal.p.earned)}</h3><h3>ประวัติส่งขยะ</h3>{modal.p.submissions.map(s=><div className="history-row" key={s.id}><Photo src={s.image} onClick={setImage}/><span className="grow">{s.category}<small>{date(s.at)}</small>{s.reason&&<small>{s.reason}</small>}</span><Badge status={s.status}/></div>)}<h3>บัญชี Coins</h3>{modal.p.ledger.map(t=><div className="ledger-row" key={t.id}><span className="grow">{t.reason}<small>{date(t.at)}</small></span><b>{t.amount>0?'+':''}{t.amount}</b></div>)}<h3>ประวัติรางวัล</h3>{modal.p.redemptions.map(r=><div className="ledger-row" key={r.id}><span>{r.name}<small>{r.code}</small>{r.completedAt&&<small>ส่งมอบ {date(r.completedAt)} · {r.staff}</small>}</span><Badge status={r.status}/></div>)}</>}
 {error&&<div className="alert" role="alert"><AlertCircle size={18}/>{error}</div>}
 </section></div>}
 {image&&<div className="lightbox" role="dialog" aria-label="ภาพขยาย" aria-modal="true" onClick={()=>setImage('')}><button autoFocus aria-label="ปิดภาพ" onClick={()=>setImage('')}><X/></button><img src={image} alt="ภาพหลักฐานขยาย"/></div>}
 </>;
}
createRoot(document.getElementById('root')).render(<App/>);
